=== zerucus/Command/src/main/resources/commands.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            attributeFormDefault="unqualified"
            elementFormDefault="qualified">

    <xsd:element name="commands">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="commandChain" type="CommandChain" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="CommandChain">
        <xsd:sequence>
            <xsd:element name="command" type="Command" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Command">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="params" type="Params" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="path" type="xsd:string" use="required"/>
                <xsd:attribute name="className" type="xsd:string" use="required"/>
                <xsd:attribute name="method" type="xsd:string" use="required"/>
                <xsd:attribute name="classInstance" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Params">
        <xsd:sequence>
            <xsd:element name="param" type="Param" minOccurs="0" maxOccurs="unbounded" />
     </xsd:sequence>
     </xsd:complexType>

    <xsd:complexType name="Param" mixed="true">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="position" type="xsd:integer" use="required"/>
                <xsd:attribute name="type" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="countries">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="pl"/>
            <xsd:enumeration value="en"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== zerucus/Command/src/main/resources/sample.xml
<?xml version="1.0"?>
<commands
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="commands.xsd">
    <commandChain name="chainName">
        <command name="instance1" path="" className="org.zerucus.command.samples.Sample" method="Constructor">
            <description>chainName [-param1] - description of param1
                -param1 - description of param1</description>
            <params>
                <param name="-param1" position="0" type="java.lang.String">Konstructor</param>
            </params>
        </command>
        <command name="instance2" path="" className="org.zerucus.command.samples.Sample" classInstance="instance1" method="objMethod">
            <description>chainName [-param1] - description of param1
                -param1 - description of param1</description>
            <params>
                <param name="-param2" position="0" type="java.lang.String">Klasa przekazana</param>
            </params>
        </command>
        <command name="instance3" path="" className="org.zerucus.command.samples.Sample" method="objMethod1">
            <description/>
            <params>
                <param name="i2" position="0" type="org.zerucus.command.samples.Sample">instance2</param>
            </params>
        </command>
    </commandChain>
</commands>

=== zerucus/Command/src/main/resources/Test.xml
<?xml version="1.0"?>
<commands
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="commands.xsd">
<commandChain name="r1">
<command name="r1" path="" className="org.zerucus.command.Test" method="Constructor">
<description>r1 [-param1] - coś tam coś tam.
-param1 - coś tam coś tam</description>
   <params>
       <param name="-param1" position="0" type="java.lang.String">Konstructor</param>
       </params>
    </command>
 <command name="r2" path="" className="org.zerucus.command.Test" classInstance="r1" method="objMethod">
<description>r1 [-param1] - coś tam coś tam.
-param1 - coś tam coś tam</description>
     <params>
      <param name="-param2" position="0" type="java.lang.String">Klasa przekazana</param>
      </params>
 </command>
 <command name="r3" path="" className="org.zerucus.command.Test" classInstance="r2" method="objMethod1">
<description>r3</description>
     <params>
      <param name="r2" position="0" type="org.zerucus.command.Test">r2</param>
      </params>
 </command>
</commandChain>
</commands>

=== zerucus/Command/sample.xml
<?xml version="1.0"?>
<commands
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="commands.xsd">
    <commandChain name="chainName">
        <command instanceName="instance1" className="org.zerucus.command.samples.Sample" method="Constructor">
            <description>chainName [-param1] - description of param1
                -param1 - description of param1</description>
            <params>
                <param name="-param1" type="java.lang.String">"Konstructor"</param>
            </params>
        </command>
        <command instanceName="instance2" className="org.zerucus.command.samples.Sample" classInstance="instance1" method="objMethod">
            <description>chainName [-param1] - description of param1
                -param1 - description of param1</description>
            <params>
                <param name="-param2" type="java.lang.String">"Klasa przekazana"</param>
            </params>
        </command>
        <command className="org.zerucus.command.samples.Sample" classInstance="instance2" method="objMethod1">
            <description/>
            <params>
                <param name="i2" type="org.zerucus.command.samples.Sample">instance2</param>
            </params>
        </command>
        <command  className="org.zerucus.command.samples.Sample" classInstance="instance2" method="method4">
            <description/>
            <params>
                <param name="i2" type="java.lang.Integer">3</param>
            </params>
        </command>
        <command className="org.zerucus.command.samples.Sample" classInstance="instance2" method="method1">
            <description/>
            <params>
                <param name="i2" type="int">56</param>
            </params>
        </command>
    </commandChain>
</commands>
